version: '3.4'

services:

  sql.data:
    image: microsoft/mssql-server-linux:latest

  nosql.data:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  levantamento.api:
    image: ${DOCKER_REGISTRY-}levantamentoapi
    build:
      context: .
      dockerfile: src/Services/Levantamento/Levantamento.Api/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq

  levantamento.signalr:
    image: ${DOCKER_REGISTRY-}levantamentosignalr
    build:
      context: .
      dockerfile: src/Services/Levantamento/Levantamento.SignalR/Dockerfile
    depends_on:
      - nosql.data
      - sql.data
      - levantamento.api
      - trecho.api

  trecho.api:
    image: ${DOCKER_REGISTRY-}trechoapi
    build:
      context: .
      dockerfile: src/Services/Trecho/Trecho.Api/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq

  apigateway:
    image: ${REGISTRY:-eshop}/ocelotapigw:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGateway/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq
      - levantamento.api
      - trecho.api